"""NeuroVoice observability package.

Public surface re-exported from :mod:`observability.metrics`. Import sites
should target the package root, not the submodule, so we can later swap the
backing implementation (e.g. OpenTelemetry bridge) without churning call
sites.
"""

from __future__ import annotations

from observability.metrics import (
    CONTENT_TYPE_LATEST,
    QUEUE_DEPTH,
    REGISTRY,
    TTS_DEPRECATED_ENDPOINT_TOTAL,
    TTS_DURATION_PER_CHAR_SECONDS,
    TTS_ERRORS,
    TTS_FIRST_AUDIO_SECONDS,
    TTS_FIRST_PCM_SECONDS,
    TTS_GATEWAY_FIRST_BYTE_SECONDS,
    TTS_INFERENCE_SECONDS,
    TTS_OUTPUT_CLIPPING_RATIO,
    TTS_OUTPUT_INTEGRATED_LUFS,
    TTS_OUTPUT_RMS,
    TTS_OUTPUT_SILENCE_RATIO,
    TTS_QUEUE_WAIT_SECONDS,
    TTS_REFERENCE_RESOLVE_SECONDS,
    TTS_REQUESTS,
    TTS_TOTAL_SECONDS,
    TTS_WORKER_PICKUP_SECONDS,
    WATERFALL_BUCKETS,
    WORKER_CAPACITY,
    WORKER_COLD_LOAD_SECONDS,
    WORKER_COUNT,
    WORKER_DLQ,
    WORKER_INFLIGHT,
    WORKER_LORA_CACHE_EVICTIONS,
    WORKER_LORA_CACHE_HITS,
    WORKER_LORA_CACHE_MISSES,
    WORKER_MODEL_INFO,
    record_waterfall,
    render_metrics,
)

__all__ = [
    "CONTENT_TYPE_LATEST",
    "QUEUE_DEPTH",
    "REGISTRY",
    "TTS_DEPRECATED_ENDPOINT_TOTAL",
    "TTS_DURATION_PER_CHAR_SECONDS",
    "TTS_ERRORS",
    "TTS_FIRST_AUDIO_SECONDS",
    "TTS_FIRST_PCM_SECONDS",
    "TTS_GATEWAY_FIRST_BYTE_SECONDS",
    "TTS_INFERENCE_SECONDS",
    "TTS_OUTPUT_CLIPPING_RATIO",
    "TTS_OUTPUT_INTEGRATED_LUFS",
    "TTS_OUTPUT_RMS",
    "TTS_OUTPUT_SILENCE_RATIO",
    "TTS_QUEUE_WAIT_SECONDS",
    "TTS_REFERENCE_RESOLVE_SECONDS",
    "TTS_REQUESTS",
    "TTS_TOTAL_SECONDS",
    "TTS_WORKER_PICKUP_SECONDS",
    "WATERFALL_BUCKETS",
    "WORKER_CAPACITY",
    "WORKER_COLD_LOAD_SECONDS",
    "WORKER_COUNT",
    "WORKER_DLQ",
    "WORKER_INFLIGHT",
    "WORKER_LORA_CACHE_EVICTIONS",
    "WORKER_LORA_CACHE_HITS",
    "WORKER_LORA_CACHE_MISSES",
    "WORKER_MODEL_INFO",
    "record_waterfall",
    "render_metrics",
]
